# -------------------------------------------------------------
# FRONTEND: DEVELOPMENT DOCKERFILE
# -------------------------------------------------------------
FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache gettext

# Copy package files first to leverage Docker layer caching
COPY package.json package-lock.json ./

# Install development dependencies
RUN npm install

# Copy the source code initially so the container can boot up properly.
# The new `docker compose watch` flag will dynamically sync any saved changes over this!
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Start Vite dev server and bind to 0.0.0.0 so Docker can map the port
#CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
CMD sh -c "envsubst < public/env.template.js > public/env.js && npm run dev -- --host"